name: Update GitLab Contribution Graph

permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * *'        # every day at midnight UTC
  workflow_dispatch:          # allow manual runs

jobs:
  screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm init -y
          npm install puppeteer

      - name: Fetch GitLab contribution calendar
        env:
          GITLAB_USERNAME: BernardoQuina
        run: node fetch-gitlab-contribs.js

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add gitlab-contribs.png
          if ! git diff --cached --quiet; then
            git commit -m "chore: update GitLab contribution graph"
            git push
          else
            echo "No updates to GitLab contribution graph."
          fi
